import type { Industry, IndustryId } from "./types";

export const INDUSTRIES: Record<IndustryId, Industry> = {
  telecom: {
    id: "telecom",
    name: "Telecommunications",
    themeId: "telecom",
    terminology: { customer: "subscriber", revenue: "ARPU", outage: "network incident" },
    defaultKpis: ["Churn", "ARPU", "NPS", "Network Uptime"],
    stakeholderArchetypes: ["CEO", "Head of Retention", "Network Ops Lead", "Customer Care Lead"],
    resourceArchetypes: ["Churn cohort", "Network monitoring report", "Support call logs", "Tariff comparison"],
  },
  banking: {
    id: "banking",
    name: "Banking",
    themeId: "banking",
    terminology: { customer: "client", revenue: "fee income" },
    defaultKpis: ["NIM", "Cost-to-Income", "NPS", "Default Rate"],
    stakeholderArchetypes: ["CFO", "Head of Risk", "Compliance Officer", "Product Lead"],
    resourceArchetypes: ["Financial report", "Risk register", "Compliance memo", "Cohort analysis"],
  },
  construction: {
    id: "construction",
    name: "Construction",
    themeId: "construction",
    terminology: { customer: "client", deliverable: "milestone" },
    defaultKpis: ["Schedule Variance", "Budget Burn", "Safety Incidents", "Open Risks"],
    stakeholderArchetypes: ["Project Director", "Site Foreman", "Contractor", "Client Sponsor"],
    resourceArchetypes: ["Blueprint", "Site log", "Safety checklist", "Budget sheet"],
  },
  manufacturing: {
    id: "manufacturing",
    name: "Manufacturing",
    themeId: "manufacturing",
    terminology: { customer: "buyer", defect: "non-conformance" },
    defaultKpis: ["OEE", "Defect Rate", "Throughput", "Inventory Days"],
    stakeholderArchetypes: ["Plant Manager", "QA Lead", "Supply Chain Lead", "Floor Supervisor"],
    resourceArchetypes: ["Production log", "QA report", "Supply chain report"],
  },
  retail: {
    id: "retail",
    name: "Retail",
    themeId: "retail",
    terminology: { customer: "shopper", revenue: "GMV" },
    defaultKpis: ["Conversion", "AOV", "Inventory Turn", "NPS"],
    stakeholderArchetypes: ["CMO", "Store Ops", "Buyer", "E-commerce Lead"],
    resourceArchetypes: ["Sales report", "Inventory snapshot", "Promo brief"],
  },
  logistics: {
    id: "logistics",
    name: "Logistics",
    themeId: "logistics",
    terminology: { customer: "shipper", delivery: "leg" },
    defaultKpis: ["On-Time Delivery", "Cost per Mile", "Damage Rate", "Utilization"],
    stakeholderArchetypes: ["Ops Director", "Fleet Lead", "Dispatcher", "Account Manager"],
    resourceArchetypes: ["Route plan", "Damage log", "Carrier report"],
  },
  it_startup: {
    id: "it_startup",
    name: "IT Startup",
    themeId: "it_startup",
    terminology: { customer: "user", revenue: "ARR" },
    defaultKpis: ["ARR", "Retention", "DAU/MAU", "Burn"],
    stakeholderArchetypes: ["CEO", "Head of Engineering", "PMM", "Customer Success"],
    resourceArchetypes: ["Product spec", "OKRs", "Metrics dashboard"],
  },
  healthcare: {
    id: "healthcare",
    name: "Healthcare",
    themeId: "healthcare",
    terminology: { customer: "patient" },
    defaultKpis: ["Wait Time", "Readmission Rate", "Patient Satisfaction", "Utilization"],
    stakeholderArchetypes: ["Medical Director", "Chief Nurse", "Compliance Officer", "Admin"],
    resourceArchetypes: ["Patient chart", "Incident report", "Audit doc"],
  },
  education: {
    id: "education",
    name: "Education",
    themeId: "education",
    terminology: { customer: "student" },
    defaultKpis: ["Enrollment", "Completion Rate", "NPS", "Cost per Student"],
    stakeholderArchetypes: ["Dean", "Program Lead", "Instructor", "Admissions"],
    resourceArchetypes: ["Cohort report", "Curriculum doc", "Survey results"],
  },
  government: {
    id: "government",
    name: "Government",
    themeId: "government",
    terminology: { customer: "citizen" },
    defaultKpis: ["Service SLA", "Citizen Satisfaction", "Cost per Case", "Backlog"],
    stakeholderArchetypes: ["Minister", "Department Head", "Policy Advisor", "Field Officer"],
    resourceArchetypes: ["Policy memo", "Service stats", "Public comment log"],
  },
  custom: {
    id: "custom",
    name: "Custom",
    themeId: "custom",
    terminology: {},
    defaultKpis: ["KPI 1", "KPI 2", "KPI 3", "KPI 4"],
    stakeholderArchetypes: ["Leader", "Manager", "IC", "Stakeholder"],
    resourceArchetypes: ["Report", "Dashboard", "Document"],
  },
};

export function getIndustry(id: IndustryId | undefined | null): Industry {
  return INDUSTRIES[id ?? "custom"] ?? INDUSTRIES.custom;
}
